config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  #get 'users/new'

  #get 'welcome/index'
  #match ':controller(/:action(/:id))', :via => :get

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates(:fname, presence: true, length: { maximum: 15 })
	validates(:lname, presence: true, length: { maximum: 15 })
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates(:email, presence: true, length: { maximum: 30 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false })
	validates(:phone, presence: true, uniqueness: true)
	validates(:housenum, length: { maximum: 5 })
	validates(:street, length: { maximum: 15 })
	validates(:town, length: { maximum: 20 })
	validates(:state, length: { maximum: 20})
	validates(:member, presence: true, length: { maximum: 20})
	validates(:payType, length: { maximum: 20} )
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      '<script> alert("hi") </script>'
      log_in user
      redirect_to user
    
    else
      #Create an error message.
      #flash.now[:danger] = 'Invalid email/password combination'
      #render 'new'
      redirect_to(controller)

     end
  end

  def destroy
  	log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
    @user = User.find(params[:id])
  end
  	
  def new
  	@user = User.new
  end
    
  def create
      @user = User.new(user_params)
      if @user.save
          log_in @user
          flash[:success] = "Welcome to the Easy Spicy!"
          redirect_to @user
      else
          render 'new'
      end
  end
    
  private 
    
      def user_params
          params.require(:user).permit(:fname, :lname, :email, :phone, :member, :password, :password_confirmation)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if (params.has_key?(:id) && params.has_key?(:var))
  		@id = params[:id]
  		@name = params[:var]
  		@name2 = params[:name2]
  		@name3 = params[:name3]
      @title = "Ashwin Chidambaram | Home";

  	end
  end

  def sample
  	@controller_message = " Hello from controller"
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def current_user
    	@current_user ||= User.find_by(id: session[:user_id])
  	end


  	# Returns true if the user is logged in, false otherwise.
  	def logged_in?
    	!current_user.nil?
  	end

  	def log_out
    	session.delete(:user_id)
    	@current_user = nil
    end


	

end

app/helpers/user_helper.rb
module UserHelper
	def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easy Spicy </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
    
      <%= yield %>
    
      
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="container"> 
        
       <div class="header">
      
            <div class="navbox">
                <%= link_to(controller: "welcome", action: "index") do%>
                <p class="nav_1">
                    Easy Spicy
                </p>
                    <!-- </a> -->
                </div>
                <% end %>

          <% if logged_in? %>
            <div class = "elseholde">
          <%= link_to "Profile", user_path(current_user), class: 'profile_link' %>
         <%= link_to "Log out", logout_path, method: :delete, class: 'profile_link'%>
            </div>
          <% else %>
            <div class = "elseholde">
            <%= link_to "Login", login_path, class: 'profile_link'%>
            <%= link_to "Sign Up", signup_path, class: 'profile_link' %>
                </div>
          <% end %>
          
        </div>
    <img class="nice_food_contain" src="/food_wallpaper.jpg" alt="rss feed" />
   
<div class="row">
    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>
    
      <%= f.label :fname, "First Name" %>
      <%= f.text_field :fname, class: 'form-control'%>
     
      <%= f.label :lname, "Last Name" %>
      <%= f.text_field :lname, class: 'form-control'%>

      <%= f.label :email %>
      <%= f.email_field :email,  class: 'form-control'%>
      
      <%= f.label :phone, "10 Digit Phone Number"%>
      <%= f.text_field :phone,  class: 'form-control'%>

      </br>
      <p class="member_type"> Member Type</p>
      <%= f.select(:member, options_for_select([['Cook', 'Cook'],['Food buyer', 'Food buyer']]),  class: 'form-control') %>
    
      <!-- <p class="member_type"> Payment Type</p>    
      <%= f.select(:payType, options_for_select([['Checks', 'Checks'],['PayPal', 'PayPal']])) %> -->
        
      </br>

      <%= f.label :password, "Password"%>
      <%= f.password_field :password,  class: 'form-control'%>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation,  class: 'form-control'%>

    
    
    <%= f.submit "Create my account", class: "createor" %>
    <% end %>
</div>

</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="container"> 

 <div class="header">
      
            <div class="navbox">
                <%= link_to(controller: "welcome", action: "index") do%>
                <p class="nav_1">
                    Easy Spicy
                </p>
                    <!-- </a> -->
                </div>
                <% end %>

          <% if logged_in? %>
            <div class = "elseholde">
          <%= link_to "Profile", user_path(current_user), class: 'profile_link' %>
         <%= link_to "Log out", logout_path, method: :delete, class: 'profile_link'%>
            </div>
          <% else %>
            <div class = "elseholde">
            <%= link_to "Login", login_path, class: 'profile_link'%>
            <%= link_to "Sign Up", signup_path, class: 'profile_link' %>
                </div>
          <% end %>
          
        </div>
      <h1>
          <%= @user.email %>
          <%= @user.fname %>
          <%= @user.lname %>
          <%= @user.member %>
      </h1>



 


</div>

app/views/welcome/index.html.erb
<!--  
<h1>Welcome to Easy Spicy </h1>
<br />
<p> Ashwin ON HEROKU AND GITHUB YOOOOOOOO EAT FOOD PLZ WORK</p>
<p> Sethu </p>
<p> Arunghghgh </p>
<p>Find me in app/views/welcome/index.html.erb</p>

<% #Comment %> 
<br /> 
<% 11.times do |i| %> 
	<%= i %> 
<% end %> 

<br /> 

<% if params.has_key?(:id) && params.has_key?(:var) %>
	<%= "ID: " + @id.to_s %> <br />
	<%= "Name: " + @name.to_s %> 
<% end %> 
<br />
<br />

-->

<!DOCTYPE html>
<html>
<head>
<meta charset ="UTF-8">
<title> <%= @title %> </title>
<%= stylesheet_link_tag "application" %>
</head>
<body>
        
    <div class="container"> 
        
        <div class="header">
      
            <div class="navbox">
                <%= link_to(controller: "welcome", action: "index") do%>
                <p class="nav_1">
                    Easy Spicy
                </p>
                    <!-- </a> -->
                </div>
                <% end %>

          <% if logged_in? %>
            <div class = "elseholde">
          <%= link_to "Profile", user_path(current_user), class: 'profile_link' %>
         <%= link_to "Log out", logout_path, method: :delete, class: 'profile_link'%>
            </div>
          <% else %>
            <div class = "elseholde">
            <%= link_to "Login", login_path, class: 'profile_link'%>
            <%= link_to "Sign Up", signup_path, class: 'profile_link' %>
                </div>
          <% end %>
          
        </div>
        <!-- Header Ends -->
        <div class="main_b1"> 
            <!-- <h1> Authentic Home Cooked Indian Food </h1>
            <h2> Welcome to my website </h2>
            <h2 class="one"> Feel free to explore my website </h2>
            <h2 class="two"> to learn  more about me and Mass Academy. </h2> color: #D10F3A -->
            <div class="plate_holder"> 
            <!-- <div class="plate_holder2"> -->
            	<img src="/dish.svg" alt="rss feed" />
            <!-- </div> -->
            </div>
            <div class="fb_main">
            	<div class="fb_sethu_contain">
            		<p class="fb_title_p">
            			Craving home cooked 
            		</p>
            		<p class="fb_title_p2">
            			Indian food?
            		</p>
            		<p class="fb_title_p3">
            			Buy authentic Indian food </br>  from chefs in your local area.
            		</p>
            	</div>

            
            </div>
        </div>
        <div class="main_b2"> 
            <!-- <h1> Authentic Home Cooked Indian Food </h1>
            <h2> Welcome to my website </h2>
            <h2 class="one"> Feel free to explore my website </h2>
            <h2 class="two"> to learn  more about me and Mass Academy. </h2> -->
            
            <div class="fb_main2">
            	<div class="fb_sethu_contain2">
            		<p class="fb_title_pa">
            			Have a passion for
            		</p>
            		<p class="fb_title_p2a">
            			cooking?
            		</p>
            		<p class="fb_title_p3a">
            			Woud you like to cook Indian  </br> food for people in your area?
            		</p>
            	</div>
            </div>
            <div class="plate_holder2"> 
            <!-- <div class="plate_holder2"> -->
            	<img src="/pot.svg" alt="cooking pot" />
            <!-- </div> -->
            </div>

        </div>
        <div class="fb_prop">
        	<div class="center_block">
        		<p class="ftitle"> 5 Star Food. </br> Without The 5 Star Price. </p>
        		<div class="rice_contain"> <img src="/rice.svg" alt="cooking pot" /> </div>
        		<div class="text_contain_f"> <p class="enjoy"> Enjoy authentic Indian meals from the comfort of your own home. A healthy and less expensive alternative to </br> eating at a restaurant. </p> </div>
        	</div>

        	<div class="left_block">
        		<p class="ftitle"> Time Is Money. </br> Spend It Wisely. </p>
        		<div class="rice_contain"> <img src="/circular-clock.svg" alt="cooking pot" /> </div>
        		<div class="text_contain_f"> <p class="enjoy"> Conveniently search for cooks in your area, and order from them directly through the website. View cooks' menu, prices, and availability. </p> </div>
        	</div>

        	<div class="right_block">
        		<p class="ftitle"> Pay Conveniently. </br> Pay Securely. </p>
        		<div class="rice_contain"> <img src="/credit-card.svg" alt="cooking pot" /> </div>
        		<div class="text_contain_f"> <p class="enjoy"> Stop searching through your wallet to find the exact amount of money to give to your chef. Easily pay using a credit card through our highly secure platform.</p> </div>
        	</div>



        </div>
       

        
        <div class="about_b"> 
            <div class="mission_s"> <p class="missions"> Our Mission </p> </div>
            <div class="sksdapper"> 
            	<div class="heart_img"> <img src="/heart.svg" alt="cooking pot" /> </div>
            	<div class="heart_text"> <p class= "hearty_texty"> Our goal is to provide a healthier and cheaper alternative to restaraunts for those who </br> don't  have the time or </br> knowledge to cook Indian food themselves. </p> </div>
            </div>  

            <div class="sksdapper"> 
            	<div class="heart_img"> <img src="/india.svg" alt="cooking pot" /> </div>
            	<div class="heart_text"> <p class= "hearty_texty"> We are striving to create a platform that connects Indians Americans through something</br> that we all love: Authentic Indian Food.
 </p> </div>
            </div>  
        </div>
    </div>
           
</body>

app/views/welcome/sample.html.erb
<h1>Welcome to Easy Spicy</h1>
<p>Find me in app/views/welcome/sample.html.erb</p>

<%= "Message from controller  :" + @controller_message %>

<%= link_to("Go to Index", 
	{ :controller => 'welcome', :action => 'index', :id => 5, :var => "Ashwin, Arun, Sethu"})%> 